name: merq

trigger:
  batch: false
  branches:
    include:
    - main
    - feature/*
    - rel/*
  paths:
    exclude:
    - docs
    - icon
pr:
  - main
  - master
  - feature/*
  - new/*
  - rel/*
  - pre/*
  - d16-*
  - d17-*

variables:
- template: /build/variables.yml@self

resources:
  repositories:
  - repository: templates
    type: github
    name: xamarin/yaml-templates
    ref: refs/heads/main
    endpoint: xamarin
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    sdl:
      policheck:
        enabled: true
        exclusionFile: $(System.DefaultWorkingDirectory)\build\PoliCheckExclusions.xml
      tsa:
        enabled: true
        configFile: $(System.DefaultWorkingDirectory)\build\tsaoptions-v2.json
    pool:
      name: AzurePipelines-EO
      image: AzurePipelinesWindows2022compliantGPT
      os: windows
    stages:
    - template: /build/stages/build.yml@self
    - template: /build/stages/upload.yml@self