name: Dependabot Approve

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write

jobs:
  dependabotApprove:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.issue.user.login == 'dependabot[bot]' && startswith(github.event.comment.body, '@gitbot dependabot-approve') }}
    steps:
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.issue.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.SERVICEACCOUNT_PAT }}